project_id = "rbvphlzhcgskoausszff"

[functions.generate-recipe-image]
verify_jwt = false

[functions.recommend-recipes]
verify_jwt = false

[functions.admin-regenerate-images]
verify_jwt = false

[functions.complete-recipe]
verify_jwt = false
